In [1]:
import numpy as np


x = np.arange(0,100,10,dtype = float) 
x

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [5]:
index = np.random.randint(0,len(x),5)
index

array([6, 7, 8, 7, 8])

In [6]:
x[index]

array([60., 70., 80., 70., 80.])

In [ ]:
a =