# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [82]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [83]:
grades = [77, 85, 56, 90, 66]
G=np.array(grades)
print("average:",np.average(G))
print("sum:",G.sum())

average: 74.8
sum: 374


### 【示範】陣列導向

In [84]:
import numpy as np
grades = [77, 85, 56, 90, 66]


最大值

In [85]:
import numpy as np
grades = [77, 85, 56, 90, 66]
G=np.array(grades)
G.max()


90

標準差

In [86]:
import numpy as np
grades = [77, 85, 56, 90, 66]
G=np.array(grades)
G.std()

12.416118556135006

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [87]:
e = 31.71
prices = [1096.95, 596.95, 896.95]
pricesNT = []
for i in prices:
    pricesNT.append(e *i)
    
print(pricesNT)



[34784.2845, 18929.2845, 28442.2845]


先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [88]:
import numpy as np
prices = [1096.95, 596.95, 896.95]
p = np.array(prices)
e = 31.71
pricesNT = p * e
print(pricesNT)

[34784.2845 18929.2845 28442.2845]


哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [89]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

這還不是我們要的最終成績啊!

In [90]:
grades * weights

array([17. , 24.5, 36. ])

### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


In [91]:
mul = grades * weights
grade = mul.sum()


### 【技巧】 一行完成成績計算

In [92]:
np.dot(grades,weights)

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [93]:
A = np.random.rand(50)
A

array([0.44144338, 0.61105945, 0.67852981, 0.11447353, 0.51169422,
       0.82249383, 0.91566915, 0.26649424, 0.34210241, 0.14790008,
       0.93067078, 0.77020142, 0.16631276, 0.8905478 , 0.5859559 ,
       0.47046227, 0.36657407, 0.93719185, 0.86640501, 0.12833301,
       0.77804002, 0.42885018, 0.64542745, 0.54748086, 0.96138998,
       0.93419641, 0.5906377 , 0.1243432 , 0.39880225, 0.60594985,
       0.88320367, 0.62653991, 0.56908663, 0.82537061, 0.51915898,
       0.43002495, 0.80351558, 0.91645977, 0.87528159, 0.02591464,
       0.11655721, 0.75848002, 0.87993128, 0.65909863, 0.15761327,
       0.76771247, 0.77872113, 0.9794924 , 0.21501329, 0.52878212])

### 【技巧】 檢查 A 的 `shape`

In [94]:
A.shape

(50,)

### 【技巧】 更改 A 的 shape

In [95]:
A.shape = (5,10)
A.shape
A

array([[0.44144338, 0.61105945, 0.67852981, 0.11447353, 0.51169422,
        0.82249383, 0.91566915, 0.26649424, 0.34210241, 0.14790008],
       [0.93067078, 0.77020142, 0.16631276, 0.8905478 , 0.5859559 ,
        0.47046227, 0.36657407, 0.93719185, 0.86640501, 0.12833301],
       [0.77804002, 0.42885018, 0.64542745, 0.54748086, 0.96138998,
        0.93419641, 0.5906377 , 0.1243432 , 0.39880225, 0.60594985],
       [0.88320367, 0.62653991, 0.56908663, 0.82537061, 0.51915898,
        0.43002495, 0.80351558, 0.91645977, 0.87528159, 0.02591464],
       [0.11655721, 0.75848002, 0.87993128, 0.65909863, 0.15761327,
        0.76771247, 0.77872113, 0.9794924 , 0.21501329, 0.52878212]])

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [96]:
A.reshape(10,5)

array([[0.44144338, 0.61105945, 0.67852981, 0.11447353, 0.51169422],
       [0.82249383, 0.91566915, 0.26649424, 0.34210241, 0.14790008],
       [0.93067078, 0.77020142, 0.16631276, 0.8905478 , 0.5859559 ],
       [0.47046227, 0.36657407, 0.93719185, 0.86640501, 0.12833301],
       [0.77804002, 0.42885018, 0.64542745, 0.54748086, 0.96138998],
       [0.93419641, 0.5906377 , 0.1243432 , 0.39880225, 0.60594985],
       [0.88320367, 0.62653991, 0.56908663, 0.82537061, 0.51915898],
       [0.43002495, 0.80351558, 0.91645977, 0.87528159, 0.02591464],
       [0.11655721, 0.75848002, 0.87993128, 0.65909863, 0.15761327],
       [0.76771247, 0.77872113, 0.9794924 , 0.21501329, 0.52878212]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [97]:
A.ravel()

array([0.44144338, 0.61105945, 0.67852981, 0.11447353, 0.51169422,
       0.82249383, 0.91566915, 0.26649424, 0.34210241, 0.14790008,
       0.93067078, 0.77020142, 0.16631276, 0.8905478 , 0.5859559 ,
       0.47046227, 0.36657407, 0.93719185, 0.86640501, 0.12833301,
       0.77804002, 0.42885018, 0.64542745, 0.54748086, 0.96138998,
       0.93419641, 0.5906377 , 0.1243432 , 0.39880225, 0.60594985,
       0.88320367, 0.62653991, 0.56908663, 0.82537061, 0.51915898,
       0.43002495, 0.80351558, 0.91645977, 0.87528159, 0.02591464,
       0.11655721, 0.75848002, 0.87993128, 0.65909863, 0.15761327,
       0.76771247, 0.77872113, 0.9794924 , 0.21501329, 0.52878212])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [98]:
np.zeros(10)
np.zeros((10,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [99]:
np.ones(10)
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 【技巧】單位矩陣

In [100]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [101]:
np.linspace(0,10,20)


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### 【技巧】`range` 的 array 版

就是 `arange`。

In [102]:
np.arange(1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [103]:
B = np.arange(10).reshape(2,5)
B

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [104]:
np.sum(B,axis=0) #一定要輸入axis

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [105]:
np.sum(B ,axis = 1) 

array([10, 35])

### 【提示】當然也有可能全部算

In [106]:
A.sum()

29.295591032875166

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [107]:
L = np.array([3, -2, -1, 5, 7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [108]:
c = np.array([True,False,False,True,True,False])

這是做啥呢? 我們可以瞬間...

In [109]:
L[c]

array([3, 5, 7])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [110]:
L>0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [111]:
L[L>0]
L

array([ 3, -2, -1,  5,  7, -3])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [112]:
C = np.arange(10)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
C[3:7]
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 【技巧】2維陣列切法

記得先列後行!

In [114]:
C1=C.reshape(2,5)
C1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [115]:
C1[:,1:3]

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [116]:
C1[1,:]

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [117]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [118]:
X = np.c_[x,y]
X

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [119]:
Y = np.r_[x,y]
Y

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [120]:
X[:,0]

array([1, 2, 3, 4])

In [121]:
X[:,1]

array([5, 6, 7, 8])

In [122]:
Y.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
Y

array([1, 2, 3, 4, 5, 6, 7, 8])